### ISSUE TITLE
backup-push "PgControl file not found"

### ISSUE THREAD

**Issue by akimbotwix** [wal-g/wal-g#1112]
### Database name
Citus PostgreSQL

# Issue description

### Describe your problem
When I run `backup-push` wal-g can't seem to find the `/var/lib/postgresql/data/pgdata/global/pg_control`. However I can verify this file exists when I `exec` into the `postgres` deployment and can verify that  `/var/lib/postgresql/data/pgdata/global/pg_control` does infact exist. 

### Please provide steps to reproduce
I have Citus deployed on bare-metal Kubernetes and working properly. I have set environment variables to connect to my exposed `psql` server (described below): 
```bash
sudo -su postgres envdir /etc/wal-g.d/env /usr/local/bin/wal-g backup-push /var/lib/postgresql/data/pgdata --pgdatabase <database>
```
```bash
INFO: 2021/10/07 04:40:54.231713 Selecting the latest backup as the base for the current delta backup...
ERROR: 2021/10/07 04:40:54.256098 It looks like you are trying to backup not pg_data. PgControl file not found: open /var/lib/postgresql/data/pgdata/global/pg_control: no such file or directory
```

### Please add config and wal-g stdout/stderr logs for debug purpose
I set environment variables using `envdir`
```bash
root@host etc/wal-g.d/env # ls
AWS_ACCESS_KEY_ID  AWS_REGION  AWS_SECRET_ACCESS_KEY  PGHOST  PGPASSWORD  PGPORT  WALG_S3_PREFIX
```

Here is my Kubernetes manifest for deploying the `citus` master. The worker deployments are very similar: 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: pg-citus-master
  namespace: targetad
  labels:
    name: citus-master
spec:
  ports:
  - port: 5432
    name: psql
  clusterIP: None
  selector:
    name: citus-master
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pg-citus-master
  namespace: targetad
spec:
  selector:
    matchLabels:
      name: citus-master
  template:
    metadata:
      labels:
        name: citus-master
        citusType: "citus-master"
    spec:
      nodeSelector:
               citus: master
      containers:
      - name: citus-master
        image: citusdata/citus:10.0.3
        args: ["-c", "archive_mode=yes", "-c", "archive_command='envdir /etc/wal-g.d/env /usr/local/bin/wal-g wal-push %p'", "-c", "archive_timeout=60" ]
        ports:
        - containerPort: 5432
          name: psql
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: target_ad
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PGPASSWORD
        <REDACTED>
        - name: POSTGRES_PASSWORD
        <REDACTED>
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_INITDB_WALDIR
          value: /var/lib/postgresql/citus/log
        volumeMounts:
        - name: whealth
          mountPath: /healthcheck
        - name: dshm
          mountPath: /dev/shm
        - name: wstorage
          mountPath: /var/lib/postgresql/data/pgdata
        - name: walog
          mountPath: /var/lib/postgresql/citus/log
        livenessProbe:
         exec:
           command:
           - ./pg_healthcheck
         initialDelaySeconds: 60
      volumes:
      - name: whealth
        hostPath:
          path: /data
      - name: dshm
        emptyDir:
          medium: Memory
      - name: wstorage
        hostPath:
          path: /data/citus/pgdata
      - name: walog
        hostPath:
          path: /data/citus/log
```
