### ISSUE TITLE
wal-g should be less smart about AWS credentials

### ISSUE THREAD

**Issue by willglynn** [wal-g/wal-g#5]
`wal-g` requires the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in order to [prepare an `aws.Config` that uses them](https://github.com/wal-g/wal-g/blob/a533befe61ddb8035bee77dfe9a23e17dcbc6e51/upload.go#L93-L96). This allows `wal-g` to return an error message early if it's not configured, but this approach breaks three other methods of supplying credentials which I actually use:

*  `AWS_PROFILE` pointing to something defined in `~/.aws/{config,credentials}`,
* EC2 instances [with dynamic credentials from an IAM role](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials), and
* Containers with dynamic credentials, both via [IAM roles for tasks](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) inside EC2 and [`iam-docker`](https://github.com/swipely/iam-docker) outside EC2

The AWS SDK for Go enables all of these by default, in addition to allowing configuration via `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. Removing the environment check and leaving `Credentials` unspecified will preserve the current behavior _and_ re-enable all the other ways that typical AWS tools search for credentials.

**Comment by willglynn** [comment]
Oh, and in case you'd like to use the default credential chain _and_ check that credentials exist before making an AWS API call:

```go
package main

import (
	"log"

	"github.com/aws/aws-sdk-go/aws/defaults"
)

func main() {
	config := defaults.Get().Config
	if _, err := config.Credentials.Get(); err != nil {
		log.Fatal("unable to get AWS credentials; please specify AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY")
	}

	// config has valid credentials
	// do stuff
}
```

**Comment by bithavoc** [comment]
Another consequence is that `AWS_SECURITY_TOKEN` is required (already reported in https://github.com/wal-g/wal-g/issues/10)

Additionally, in order to support other non-official S3 implementations such as https://minio.io/ we would need to be able to setup a few custom settings:
```
Endpoint:         aws.String(os.Getenv("AWS_ENDPOINT")),
DisableSSL:       aws.Bool(os.Getenv("AWS_DISABLE_SSL") == "true"),
S3ForcePathStyle: aws.Bool(os.Getenv("AWS_S3_FORCE_PATH_STYLE") == "true"),
```

Example:
```
WALE_S3_PREFIX: s3://backups/wal-g
AWS_ENDPOINT: http://minio:9000
```

`S3ForcePathStyle` is required so the aws go sdk doesn't try to call `http://backups.s3.amazonaws.com/wal-g` and instead reach the minio server using sub path resources as in `http://minio:9000/backups/wal-g`.

With the aforementioned changes the following docker-compose.yml works correctly:

```
postgres:
    image: postgres:9
    volumes:
      - "./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
      - "./walgbin/wal-g:/var/lib/postgresql/data/wal-g"
    environment:
      AWS_ACCESS_KEY_ID: "73R08HT3BEIULJTUWTD9"
      AWS_SECRET_ACCESS_KEY: "gvaLgHrcxIKV9SqrzRjsFJTJC82Djlio5EMN3Btb"
      WALE_S3_PREFIX: s3://backups/wal-g
      AWS_ENDPOINT: http://minio:9000
      AWS_REGION: us-east-1
      AWS_SECURITY_TOKEN: ""
    links:
      - minio
      - walg
  minio:
    image: minio/minio:latest
    command: minio server /export
    expose:
      - "9000"
    ports:
      - "10500:9000"
    environment:
      MINIO_ACCESS_KEY: "73R08HT3BEIULJTUWTD9"
      MINIO_SECRET_KEY: "gvaLgHrcxIKV9SqrzRjsFJTJC82Djlio5EMN3Btb"
      MINIO_REGION: us-east-1
```
